
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                            - Bip  -                                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
\*-----------------------------------------------------------------------------------------------4246-*/

#include "../../../../program_connector/Functions.c"

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

void hluti_2()
{
	for (int i = 1;i <= 5; i++){
			MoveForward_cm(50*i);
			wait1Msec(2000);
			MoveBackward_cm(50*i);
			wait1Msec(2000);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
