#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in2,    lightSensor,    sensorReflection)
#pragma config(Sensor, in5,    ArmeEncoder,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, touchSensor,    sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1692728)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           handMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1692728)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../../program_connector/Functions.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task DriveStraight()
{
	while(true){
	    if (abs(SensorValue[rightEncoder]) + 20 < abs(SensorValue[leftEncoder])){
	        if (att){
	            motor[rightMotor] = FullPower+10;
	            motor[leftMotor] = (FullPower-10);
	        }

	    }else if(abs(SensorValue[leftEncoder]) + 20 < abs(SensorValue[rightEncoder])){
	      if (att){
	            motor[rightMotor] =(FullPower-10);
	            motor[leftMotor] = (FullPower+10);
	        }

	    }else{
	        if (att){
	            motor[rightMotor] = FullPower;
	            motor[leftMotor] = FullPower;
	        	}

	    }

	}
}

void printRandoms(int lower, int upper) 
{ 
	int i; 
	for (i = 0; i < 1; i++) { 
		int num = (rand() % 
		(upper - lower + 1)) + lower; 
		return num
	} 
} 






void MoveForward(bool att)
{
	StartTask(DriveStraight);
}

task main()
{
	StartTask(stop);

	while(true)
	{
		if(SensorValue[sonar] > 40)
		{
			MoveForward(true);
		}else{
			StopTask(DriveStraight);
			ResetMotor();
			int random_number =  printRandoms(0, 1); 
			if (random_number == 1){	
				TurnRight(90.0);
			}else{
				TurnLeft(90.0);
			}


		}
		while(SensorValue[lightSensor] > 200) // While the ambient lightSensor reads a value less than 200
		{
			StopTask(DriveStraight);
			ResetMotor();
		}
	}
}



