#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Bip  -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/

string lcd_array[] = {"verkefni 2","Hluti 1","Hluti 2","Hluti 3","verkefni 3","verkefni 4","verkefni 5","verkefni 6","verkefni 7","----------------------"};

int index = 0;
int index2 = 1;

bool afram;

void LCD(string text_1, string text_2)
{
  clearLCDLine(0);
	clearLCDLine(1);
	displayLCDPos(0,0);
	displayNextLCDString(text_1);
	displayLCDPos(1,0);
	displayNextLCDString(text_2);
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	while(true){
		if(nLCDButtons == 4){
			if(index >= 2 && index < 8){
				index ++;
			}else if(index < 8){
				index = 0;
				index2 ++;
				if(index2 > 3){
					index = 4;
					index2 = 9;
				}
			}

		}

		if(nLCDButtons == 1){
			if(index > 4){
				index --;
				index2 = 9;
			}else if(index >= 0 && index2 > 1){
				if(index2 == 9){index2 = 4;};
				index = 0;
				index2 --;

			}

		}
		if(nLCDButtons == 2){
			afram = true;
			while(afram)
			{
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDPos(0,6);
				displayNextLCDString("Run");
				displayLCDPos(1,2);
				displayNextLCDString("Yes");
				displayLCDPos(1,12);
				displayNextLCDString("No");
				wait1Msec(250);
				if(nLCDButtons == 4){
					afram = false;
				}
			}
		}

		LCD(lcd_array[index],lcd_array[index2]);
		wait1Msec(250);
	}
}
